### ISSUE TITLE
Cannot run project 

### ISSUE THREAD

**Issue by thuy4tbn99** [Dec1mo/Vietnamese-Address-Parser#1]
![image](https://user-images.githubusercontent.com/42961260/126461320-a6bdc4f3-97ef-4101-af6d-003d79353157.png)

Hi, 

I Try run your code: python excel_parser/excel_parser.py
But This raise the error. No such file standard_adress.xls
Can you help me? 

Thanh you

**Comment by Dec1mo** [comment]
I'm so sorry, I didn't watch this project so I didn't notice your issue.
Unfortunately, my computer was broken without any backup. So I don't remember the format and number of data files I used.
You can get/crawl the data files here: 
- https://bandolamnghiep.com/file-excel-tat-cac-cac-xa-huyen-tinh-thanh-pho-o-viet-nam-2021/
- https://github.com/Dec1mo/Coc-Coc-Map-crawler

**Comment by baonguyen267** [comment]
So, where's location of standard_address.xls in this project?

**Comment by Dec1mo** [comment]
The above link (https://bandolamnghiep.com/file-excel-tat-cac-cac-xa-huyen-tinh-thanh-pho-o-viet-nam-2021/) contains standard_address.xls file. 

Please read the code to know where to put it since I don't maintain this repo any more.
Thanks
