### ISSUE TITLE
Thiếu file data

### ISSUE THREAD

**Issue by minhduc210196** [Dec1mo/Vietnamese-Address-Parser#4]
Tôi đã thử chạy theo hướng dẫn trên git nhưng dường như đang thiếu data bạn có thể giải thích giúp  tôi được không tôi đang mới học code nên chưa được hiểu rõ 
![image](https://github.com/Dec1mo/Vietnamese-Address-Parser/assets/147492971/dd35359b-c1fa-4b27-8c6e-0305b5020c9d)

**Comment by Dec1mo** [comment]
Please give https://github.com/Dec1mo/Vietnamese-Address-Parser/issues/1 a look.
Thanks.
